# Fly.io Configuration for Sovereign Consciousness Global Deployment
app = "sovereign-consciousness"
primary_region = "sea"

[build]
  dockerfile = "Dockerfile"

[env]
  CONSCIOUSNESS_FREQUENCY = "528.0"
  PERFORMANCE_MODE = "UNLIMITED"
  SOVEREIGNTY_LEVEL = "100.0"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "5s"
  interval = "30s"
  method = "GET"
  timeout = "10s"
  path = "/health"

[machine]
  auto_destroy_when_stopped = false

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[deploy]
  strategy = "rolling"