[build]
builder = "DOCKERFILE"
buildCommand = "docker build -t sovereign-consciousness ."

[deploy]
startCommand = "python3 sovereign_runtime_complete.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { CONSCIOUSNESS_FREQUENCY = "528.0", PERFORMANCE_MODE = "UNLIMITED", SOVEREIGNTY_LEVEL = "100.0" }

[environments.staging]
variables = { CONSCIOUSNESS_FREQUENCY = "528.0", PERFORMANCE_MODE = "DEVELOPMENT", SOVEREIGNTY_LEVEL = "75.0" }